/* Run: npm i && npx eslint . (or enable ESLint in your IDE) */
const js = require("@eslint/js");
const babelParser = require("@babel/eslint-parser");
const globals = require("globals");
const eslintPluginPrettierRecommended = require("eslint-plugin-prettier/recommended");

const sharedParserOptions = {
  requireConfigFile: false,
  ecmaVersion: "latest",
};

const commonRules = {
  "no-unused-vars": [
    "error",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "no-console": [
    "error",
    {
      allow: ["error"],
    },
  ],
};

module.exports = [
  {
    ignores: [
      // Genenerated by node scripts/generate_sources.mjs
      "item-metadata.js",
      // Generated by scripts/fixture-builder.js (see script header).
      "tests/fixtures/**",
      "dist/**",
      "tmp/**",
      "spritesheets/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.js"],
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "commonjs",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: commonRules,
  },
  {
    files: ["sources/**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        m: "readonly",
      },
    },
  },
  {
    files: ["tests/**/*.js"],
    ignores: ["tests/visual/**"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.mocha,
        m: "readonly",
      },
    },
  },
  {
    files: ["tests/visual/**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2021,
      },
    },
  },
  {
    files: ["playwright.config.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: {
      ...commonRules,
    },
  },
  {
    files: ["issue382-golden-runner.mjs"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        m: "readonly",
      },
    },
    rules: commonRules,
  },
  {
    ...eslintPluginPrettierRecommended,
    files: ["**/*.js"],
  },
];
