name: Validate site sources

on:
  push:
    branches:
      - master
      - full_rewrite
  pull_request:
    branches:
      - master
      - full_rewrite

jobs:
  validate_site_sources:
    name: Validate site sources
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run browser tests
        run: |
          npx http-server -p 8080 &
          SERVER_PID=$!
          sleep 3
          echo "Fetching test results from browser..."

          # Use Chrome headless with virtual time budget to let JS execute
          # Increase virtual-time-budget if tests take longer (value is in milliseconds)
          timeout 30 google-chrome --headless --disable-gpu \
            --virtual-time-budget=10000 \
            --dump-dom "http://localhost:8080/tests_run.html" > rendered.html || true

          sleep 1

          echo "Test results:"
          cat rendered.html

          if grep -q 'id="test-status">PASS' rendered.html; then
            echo "✓ All browser tests passed"
            kill $SERVER_PID
          else
            echo "✗ Browser tests failed"
            kill $SERVER_PID
            exit 1
          fi

      - name: Validate site sources generation
        run: |
          node scripts/generate_sources.cjs
      - name: Assert git diff
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Differences found after (re)generation of the site sources"
            echo "Please refer to the README in order to learn how to generate the site's sources properly."
            exit -1
          fi
