name: Validate site sources

on:
  push:
    branches:
      - master
      - full_rewrite
  pull_request:
    branches:
      - master
      - full_rewrite

jobs:
  validate_site_sources:
    name: Validate site sources
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Validate site sources generation
        run: |
          node scripts/generate_sources.cjs
      - name: Assert git diff
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Differences found after (re)generation of the site sources"
            echo "Please refer to the README in order to learn how to generate the site's sources properly."
            exit -1
          fi
